spring:
  application:
    name: "proto-transaction-service"
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      acks: "all"
    consumer:
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      schema.registry.url: "http://localhost:8081"
      auto.register.schemas: true
    streams:
      application-id: "proto-transaction-kstream"
      properties:
        processing.guarantee: exactly_once_beta
        commit.interval.ms: 50
        producer:
          acks: "all"

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info
